commit

diff --git a/scripts/pandoctools-source b/scripts/pandoctools-source
--- a/scripts/pandoctools-source
+++ b/scripts/pandoctools-source
@@ -15,6 +15,6 @@ all_but_first="${@:2}"
 if [[ -f "${full_path}" ]]; then
     source "${full_path}" "${all_but_first}"
 else
-    echo "Error: $1 was not found in \$PATH or is not a file."
+    echo "Error: $1 was not found in \$PATH or is not a file." >&2
     exit 1
 fi
